# coding: utf-8

"""
    Dashboards API

    Manage ThousandEyes Dashboards.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class RefreshRate(str, Enum):
    """
    Auto-refresh interval for a dashboard. Use `off` to disable auto-refresh.
    """

    """
    allowed enum values
    """
    OFF = 'off'
    ENUM_2M = '2m'
    ENUM_5M = '5m'
    ENUM_10M = '10m'
    ENUM_15M = '15m'
    ENUM_30M = '30m'
    ENUM_60M = '60m'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RefreshRate from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Handle unknown values"""
        return cls.UNKNOWN

