# flake8: noqa

# import apis into api package
from thousandeyes_sdk.endpoint_instant_tests.api.agent_to_server_instant_scheduled_test_api import AgentToServerInstantScheduledTestApi
from thousandeyes_sdk.endpoint_instant_tests.api.http_server_instant_scheduled_test_api import HttpServerInstantScheduledTestApi
from thousandeyes_sdk.endpoint_instant_tests.api.run_existing_test_api import RunExistingTestApi

