# coding: utf-8

"""
    ThousandEyes for OpenTelemetry

     Configure ThousandEyes to stream or push test data to a OpenTelemetry compliant endpoint with the ThousandEyes for OpenTelemetry API. 

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from streaming_api.models.put_stream import PutStream

class TestPutStream(unittest.TestCase):
    """PutStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutStream:
        """Test PutStream
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutStream`
        """
        model = PutStream()
        if include_optional:
            return PutStream(
                custom_headers = {"Authorization":"*****","Content-Type":"*****"},
                tag_match = [{"objectType":"test","key":"keyA","value":"valueA"},{"objectType":"test","key":"keyB","value":"valueB"}],
                enabled = False
            )
        else:
            return PutStream(
        )
        """

    def testPutStream(self):
        """Test PutStream"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
