# coding: utf-8

"""
    Tests API

    This API supports listing, creating, editing, and deleting Cloud and Enterprise Agent (CEA) based tests. 

    The version of the OpenAPI document: 7.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from tests.models.alert_rounds_violation_mode import AlertRoundsViolationMode

class TestAlertRoundsViolationMode(unittest.TestCase):
    """AlertRoundsViolationMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertRoundsViolationMode(self):
        """Test AlertRoundsViolationMode"""
        # inst = AlertRoundsViolationMode()

if __name__ == '__main__':
    unittest.main()
