# flake8: noqa

# import apis into api package
from thousandeyes_sdk.internet_insights.api.internet_insights_catalog_providers_api import InternetInsightsCatalogProvidersApi
from thousandeyes_sdk.internet_insights.api.internet_insights_outages_api import InternetInsightsOutagesApi

