# coding: utf-8

"""
    Test Snapshots API

    Creates a new test snapshot in ThousandEyes.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from snapshots.models.test_interval import TestInterval

class TestTestInterval(unittest.TestCase):
    """TestInterval unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestInterval(self):
        """Test TestInterval"""
        # inst = TestInterval()

if __name__ == '__main__':
    unittest.main()
