# coding: utf-8

"""
    Alerts API

     ## Overview Manage all alerts, alert rules and alert suppression windows.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class Severity(str, Enum):
    """
    The severity of the alert.
    """

    """
    allowed enum values
    """
    INFO = 'info'
    MAJOR = 'major'
    MINOR = 'minor'
    CRITICAL = 'critical'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Severity from a JSON string"""
        return cls(json.loads(json_str))


