# coding: utf-8

"""
    Tests API

     ### Overview This API supports listing, creating, editing, and deleting Cloud and Enterprise Agent (CEA) based tests.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from tests_api.models.alert_type import AlertType

class TestAlertType(unittest.TestCase):
    """AlertType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertType(self):
        """Test AlertType"""
        # inst = AlertType()

if __name__ == '__main__':
    unittest.main()
