# coding: utf-8

"""
    Endpoint Agents API

    Manage ThousandEyes Endpoint Agents using this API.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agents_api.models.agent_search_request import AgentSearchRequest

class TestAgentSearchRequest(unittest.TestCase):
    """AgentSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentSearchRequest:
        """Test AgentSearchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentSearchRequest`
        """
        model = AgentSearchRequest()
        if include_optional:
            return AgentSearchRequest(
                search_filters = agents_api.models.agent_search_request_search_filters.AgentSearchRequest_searchFilters(
                    agent_name = [
                        'myagent-1234'
                        ], 
                    computer_name = [
                        'DESKTOP-45AE8'
                        ], 
                    username = ["picard"], 
                    platform = [
                        'mac'
                        ], 
                    os_version = [
                        'Version 10.15.2'
                        ], 
                    location_country_iso = [
                        'FR'
                        ], 
                    location_subdivision1_code = [
                        'ENG'
                        ], 
                    location_city = [
                        'Paris'
                        ], )
            )
        else:
            return AgentSearchRequest(
        )
        """

    def testAgentSearchRequest(self):
        """Test AgentSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
