# coding: utf-8

"""
    Endpoint Agents API

    Manage ThousandEyes Endpoint Agents using this API.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from agents_api.models.wireless_profile import WirelessProfile

class TestWirelessProfile(unittest.TestCase):
    """WirelessProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WirelessProfile:
        """Test WirelessProfile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WirelessProfile`
        """
        model = WirelessProfile()
        if include_optional:
            return WirelessProfile(
                bssid = '00:11:22:aa:bb:cc',
                ssid = 'GuestWiFi',
                rssi = -36,
                channel = 48,
                phy_mode = '802.11ac'
            )
        else:
            return WirelessProfile(
        )
        """

    def testWirelessProfile(self):
        """Test WirelessProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
