# coding: utf-8

"""
    Dashboards API

    Manage ThousandEyes Dashboards.

    The version of the OpenAPI document: 7.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dashboards.models.stacked_area_chart_datasource import StackedAreaChartDatasource

class TestStackedAreaChartDatasource(unittest.TestCase):
    """StackedAreaChartDatasource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStackedAreaChartDatasource(self):
        """Test StackedAreaChartDatasource"""
        # inst = StackedAreaChartDatasource()

if __name__ == '__main__':
    unittest.main()
