# coding: utf-8

"""
    Dashboards API

    Manage ThousandEyes Dashboards.

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dashboards.models.api_default_timespan import ApiDefaultTimespan

class TestApiDefaultTimespan(unittest.TestCase):
    """ApiDefaultTimespan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiDefaultTimespan:
        """Test ApiDefaultTimespan
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiDefaultTimespan`
        """
        model = ApiDefaultTimespan()
        if include_optional:
            return ApiDefaultTimespan(
                duration = 7200,
                start = '2023-05-16T10:14:28Z',
                end = '2023-05-16T11:14:28Z'
            )
        else:
            return ApiDefaultTimespan(
        )
        """

    def testApiDefaultTimespan(self):
        """Test ApiDefaultTimespan"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
