# coding: utf-8

"""
    Instant Tests API

    The Instant Tests API operations lets you create and run new instant tests. You will need to be an Account Admin.  The response does not include the immediate test results. Use the Test Results endpoints to get test results after creating and executing an instant test. You can find the URLs for these endpoints in the _links section of the test definition that is returned when you create the instant test. 

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NetworkProviderType(str, Enum):
    """
    Classification of the agent's network provider.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'unknown'
    ISP = 'isp'
    CDN = 'cdn'
    STUB = 'stub'
    CLOUD_MINUS_PROVIDER = 'cloud-provider'
    CARRIER = 'carrier'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkProviderType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Handle unknown values"""
        return cls.UNKNOWN

