# coding: utf-8

"""
    Dashboards API

    Manage ThousandEyes Dashboards

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dashboards_api.models.api_agent_location import ApiAgentLocation

class TestApiAgentLocation(unittest.TestCase):
    """ApiAgentLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiAgentLocation:
        """Test ApiAgentLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiAgentLocation`
        """
        model = ApiAgentLocation()
        if include_optional:
            return ApiAgentLocation(
                latitude = 37.77493,
                longitude = -122.41942,
                location_name = 'San Francisco, California, US'
            )
        else:
            return ApiAgentLocation(
        )
        """

    def testApiAgentLocation(self):
        """Test ApiAgentLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
