# coding: utf-8

"""
    Dashboards API

    Manage ThousandEyes Dashboards

    The version of the OpenAPI document: 7.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dashboards_api.models.generate_dashboard_snapshot_request import GenerateDashboardSnapshotRequest

class TestGenerateDashboardSnapshotRequest(unittest.TestCase):
    """GenerateDashboardSnapshotRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateDashboardSnapshotRequest:
        """Test GenerateDashboardSnapshotRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateDashboardSnapshotRequest`
        """
        model = GenerateDashboardSnapshotRequest()
        if include_optional:
            return GenerateDashboardSnapshotRequest(
                start_date = '2023-05-16T10:14:28Z',
                end_date = '2023-05-16T10:14:28Z',
                display_name = 'snapshot from API',
                dashboard_id = '646f4d2ce3c99b0536c3821e',
                anonymize_data = True,
                timezone = 'PST',
                expiration_date = '2023-05-16T10:14:28Z'
            )
        else:
            return GenerateDashboardSnapshotRequest(
        )
        """

    def testGenerateDashboardSnapshotRequest(self):
        """Test GenerateDashboardSnapshotRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
